export const FETCH_GOODS = 'FETCH_GOODS';

export const RESTORE_CART_ITEMS = 'RESTORE_CART_ITEMS';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const REMOVE_ITEMS_FROM_CART_BY_NAME = 'REMOVE_ITEMS_FROM_CART_BY_NAME';
export const CLEAR_CART = 'CLEAR_CART';